### ISSUE TITLE
Links zu Impressum etc tun nicht im post

### ISSUE THREAD

**Issue by Pike** [ewolff/software-architektur.tv#3]
Die links in https://github.com/ewolff/software-architektur.tv/blob/f2596bd91f8dc36e1b080a3485345c4e0285a8c7/_includes/page-footer.html#L5-L6 im page footer sollten absolute links sein, und nicht relative.

**Comment by ewolff** [comment]
Danke für den Hinweis! 🙂

**Comment by Pike** [comment]
Das hat leider nicht geholfen. Jenkins scheint die wieder umzumodeln?

**Comment by ewolff** [comment]
Danke für den Hinweis!
